# Micromamba environment setup

# Default tool versions, override with --bazel and --codechecker
MM_DEFAULT_BAZEL_VERSION="7.7.1"
MM_DEFAULT_CODECHECKER_VERSION="6.27.3"

# Download URL
MM_MICROMAMBA_DOWNLOAD_URL="https://micro.mamba.pm/api/micromamba/linux-64/latest"

# Verbosity can be used by any function
MM_VERBOSE=""

function mm_log() {
    [[ -n "$MM_VERBOSE" ]] && echo "[micromamba] $@"
    return 0
}

function mm_info() {
    echo "[micromamba] $@"
}

function mm_command() {
    local command="$@"
    mm_log "==================================================================="
    mm_log "> ${command}"
    eval "${command}"
}

function mm_usage() {
    local this_file="$1"

    echo "Usage: source $this_file [options] [env]   # Create and/or activate"
    echo "       bash   $this_file [options] [env]   # Create only"
    echo
    echo "Options:"
    echo "  --bazel=VERSION         Bazel version (default: $MM_DEFAULT_BAZEL_VERSION)"
    echo "  --codechecker=VERSION   CodeChecker version (default: $MM_DEFAULT_CODECHECKER_VERSION)"
    echo "  --force                 Recreate the environment even if it exists"
    echo "  -v, -vv                 Verbose output"
    echo "  -h, --help              This help message"
    echo
    echo "The environment name defaults to 'dev'."
    echo
    echo "Examples:"
    echo "  source $this_file                            Activate [dev]"
    echo "  source $this_file --force                    Recreate and activate [dev]"
    echo "  source $this_file --bazel=8.5.1 bazel8       Create and activate [bazel8]"
    echo "  bash   $this_file --codechecker=6.26 cc26    Create [cc26] to activate later"
}

# Parse the command line into the variables named by the first four arguments
function mm_parse_args() {
    local -n env_name_ref="$1"
    local -n bazel_ref="$2"
    local -n codechecker_ref="$3"
    local -n force_ref="$4"
    local this_file="$5"
    shift 5

    env_name_ref="dev"
    bazel_ref="$MM_DEFAULT_BAZEL_VERSION"
    codechecker_ref="$MM_DEFAULT_CODECHECKER_VERSION"
    force_ref=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -v)
                MM_VERBOSE=1
                ;;
            -vv)
                MM_VERBOSE=2
                ;;
            --bazel=*)
                bazel_ref="${1#*=}"
                ;;
            --bazel)
                bazel_ref="$2"
                shift
                ;;
            --codechecker=*)
                codechecker_ref="${1#*=}"
                ;;
            --codechecker)
                codechecker_ref="$2"
                shift
                ;;
            --force)
                force_ref=1
                ;;
            -h | --help)
                mm_usage "$this_file"
                return 2
                ;;
            -*)
                mm_info "ERROR: Unknown option: $1"
                mm_usage "$this_file"
                return 1
                ;;
            *)
                env_name_ref="$1"
                ;;
        esac
        shift
    done
    return 0
}

# Generate an environment file from the template
function mm_generate_env_file() {
    local template="$1"
    local output="$2"
    local bazel_version="$3"
    local codechecker_version="$4"

    if [ ! -f "$template" ]; then
        mm_info "ERROR: No environment template found: $template"
        return 1
    fi
    {
        echo "# Generated by init.sh from $(basename $template), do not edit"
        sed -e "/^#/d" \
            -e "s/@BAZEL_VERSION@/$bazel_version/" \
            -e "s/@CODECHECKER_VERSION@/$codechecker_version/" \
            "$template"
    } > "$output"
    [[ "$MM_VERBOSE" -ge 2 ]] && cat "$output"
    return 0
}

# Install micromamba, see https://mamba.readthedocs.io
function mm_install() {
    local install_dir="$1"

    if [ -f "$install_dir/bin/micromamba" ]; then
        mm_info "Using: $install_dir/bin/micromamba"
        return 0
    fi
    mm_info "Installing to $install_dir/bin ..."
    pushd "$install_dir" > /dev/null
    mm_log "Downloading $MM_MICROMAMBA_DOWNLOAD_URL"
    curl -Ls $MM_MICROMAMBA_DOWNLOAD_URL | tar -xvj bin/micromamba
    popd > /dev/null
}

# Make micromamba available in the current shell
function mm_hook() {
    local install_dir="$1"

    export MAMBA_EXE="$install_dir/bin/micromamba"
    export MAMBA_ROOT_PREFIX="$install_dir/micromamba"
    eval "$($MAMBA_EXE shell hook --shell bash --root-prefix $MAMBA_ROOT_PREFIX)"
    mm_log "MAMBA_EXE=$MAMBA_EXE"
    mm_log "MAMBA_ROOT_PREFIX=$MAMBA_ROOT_PREFIX"
    if [[ "$MM_VERBOSE" -ge 2 ]]; then
        mm_command "micromamba info"
        mm_command "micromamba env list"
    fi
    return 0
}

function mm_create_env() {
    local env_name="$1"
    local env_file="$2"
    local env_dir="$MAMBA_ROOT_PREFIX/envs/$env_name"
    local verbosity="--quiet"

    [[ "$MM_VERBOSE" -ge 2 ]] && verbosity=""
    # The environment cannot be removed while it is active
    micromamba deactivate
    if [ -d "$env_dir" ]; then
        # Make the leftover environment modifiable to allow micromamba
        # to delete bazel cache folders during its setup
        mm_info "Changing permissions for previous environment [$env_name]..."
        chmod -R +w "$env_dir"
        mm_info "Removing previous environment [$env_name]..."
        micromamba env remove --name "$env_name" --yes $verbosity
    fi
    mm_info "Creating environment [$env_name]..."
    micromamba create --file "$env_file" --name "$env_name" --yes $verbosity
}

# Print tool versions: Bazel and CodeChecker by default, all tools with -v,
# and their location as well with -vv
function mm_print_versions() {
    local tools="bazel CodeChecker"
    local all_tools="python3 bazel CodeChecker clang clang-tidy clang-extdef-mapping
                     diagtool buildifier pylint pycodestyle pytest gcc g++"
    local tool version path

    [[ -n "$MM_VERBOSE" ]] && tools="$all_tools"
    mm_info "Tool versions:"
    for tool in $tools; do
        path=$(command -v $tool 2>/dev/null)
        if [ -z "$path" ]; then
            mm_info "$(printf '  %-22s %s' "$tool" "NOT FOUND")"
            continue
        fi
        if [[ "$tool" == "CodeChecker" ]]; then
            # CodeChecker prints a table instead of a version string
            version=$(CodeChecker version 2>/dev/null |
                      grep -m 1 -Po '(?<=package version \| ).*' | xargs)
        elif [[ "$tool" == "bazel" ]]; then
            # Only 'bazel version' reports the version reliably, see issue #267
            version=$(bazel version --gnu_format 2>/dev/null |
                      grep -m 1 -Po '^bazel \K[\d.]+')
        else
            version=$($tool --version 2>&1 | grep -m 1 -Po '\d[\d.]*' | head -1)
        fi
        if [[ "$MM_VERBOSE" -ge 2 ]]; then
            # Paths inside the current directory are shown relative to it
            mm_info "$(printf '  %-22s %-10s (%s)' \
                       "$tool" "${version:-unknown}" "${path#$PWD/}")"
        else
            mm_info "$(printf '  %-22s %s' "$tool" "${version:-unknown}")"
        fi
    done
}

function mm_activate_env() {
    local env_name="$1"

    micromamba activate "$env_name" || return 1
    mm_print_versions
    mm_info "To exit session run: micromamba deactivate"
}

function mm_main() {
    # Activation modifies the current shell, therefore it requires sourcing
    local this_file="${BASH_SOURCE[0]}"
    local sourced=1
    local this_dir env_name bazel_version codechecker_version force
    local env_file status

    [[ "$this_file" == "$0" ]] && sourced=0
    this_dir="$( cd "$( dirname "$this_file" )" &> /dev/null && pwd )"
    mm_parse_args env_name bazel_version codechecker_version force \
        "$this_file" "$@"
    status=$?
    # Help was requested, nothing left to do
    [[ "$status" == "2" ]] && return 0
    [[ "$status" == "0" ]] || return 1

    mm_log "Environment: $env_name"
    mm_log "   Location: $this_dir"

    mm_install "$this_dir" || return 1
    mm_hook "$this_dir"

    # An existing environment is reused, unless recreation is forced
    if [ -d "$MAMBA_ROOT_PREFIX/envs/$env_name" ] && [ -z "$force" ]; then
        mm_info "Using existing environment [$env_name]"
    else
        env_file="$MAMBA_ROOT_PREFIX/envs/$env_name.yaml"
        mkdir -p "$MAMBA_ROOT_PREFIX/envs"
        mm_generate_env_file "$this_dir/env.yaml" "$env_file" \
            "$bazel_version" "$codechecker_version" || return 1
        mm_log "Environment file: $env_file"
        mm_create_env "$env_name" "$env_file" || return 1
    fi

    if [[ "$sourced" == "0" ]]; then
        mm_info "Not sourced, environment [$env_name] is not activated"
        mm_info "To activate it run:"
        mm_info "       source $this_dir/init.sh $env_name"
        return 0
    fi
    mm_activate_env "$env_name"
}

# Remove everything this script defined, it must not leak into the shell.
# Removing the running functions is safe, bash keeps their body in memory.
function mm_cleanup() {
    unset MM_DEFAULT_BAZEL_VERSION
    unset MM_DEFAULT_CODECHECKER_VERSION
    unset MM_MICROMAMBA_DOWNLOAD_URL
    unset MM_VERBOSE
    unset -f mm_log
    unset -f mm_info
    unset -f mm_command
    unset -f mm_usage
    unset -f mm_parse_args
    unset -f mm_generate_env_file
    unset -f mm_hook
    unset -f mm_install
    unset -f mm_create_env
    unset -f mm_print_versions
    unset -f mm_activate_env
    unset -f mm_main
    unset -f mm_cleanup
    unset -f mm_exit
}

function mm_exit() {
    local status="$1"
    mm_cleanup
    return "$status"
}

mm_main "$@"
mm_exit $?
